### PR TITLE
Support i8 type

### PR DESCRIPTION
**Pull request by Tuxity**
See #37

Tested and work with my project, maybe I miss some stuff

### CODE REVIEW

**Comment by gggeek** [comment]
At first sight it looks good.
The lib would miss a way to flag an error when an i8 is received and php does not support 64 bits though...

**Comment by Tuxity** [comment]
Hmmm where it would be better to add this test ?

**Comment by gggeek** [comment]
good question. Whenever decoding an i8 tag is safe, but it might be slow...

**Comment by gggeek** [comment]
Merged, but a few twists have been added.

I8 can not be considered synonym to int/i4, as it is not part of the xmlrpc spec.

**Pull request merged**
